# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            tcmorris
tagline:          'umbraco web developer'
description:      'Ramblings of a web dev living in Bristol, UK'
url:              http://tcmorris.net

google:
  analytics:	  'UA-60083725-1'

meta:
  description:    'Thomas Morris is a web developer who specialises in Umbraco and ASP.NET'
  keywords:       'Web developer, Umbraco, ASP.NET'
  
author:
  name:           'Thomas Morris'
  url:            https://twitter.com/mozzy16

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tcmorris/tcmorris.github.io