# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            tcmorris
tagline:          '.net web developer'
description:      '.net web developer'
url:              https://tcmorris.net
enforce_ssl:      tcmorris.net
paginate:         4

# Custom vars
google:
  analytics:	    'UA-60083725-1'

disqus:
  username:		    'tcmorris'

meta:
  description:    'Thomas Morris is a web developer who specialises in Umbraco and ASP.NET'
  keywords:       'Web developer, umbraco, asp.net, c#, csharp, mvc'

author:
  name:           'Thomas Morris'
  email:		      'hello@tcmorris.net'
  twitter:        mozzy16
  image: 		      /public/images/thomasmorris.jpeg

github:
  repo:           https://github.com/tcmorris/tcmorris.github.io

umbraco:
  logo:           /public/images/umbraco_badge.jpg
  link:           https://umbraco.com/certified-partners/find-a-certified-developer/details?id=6bb58bc7-772d-4d71-99da-b924cb232066