# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            tcmorris
tagline:          '#umbraco web developer'
description:      'Ramblings of a web dev living in Bristol, UK'
url:              http://tcmorris.net

author:
  name:           'Thomas Morris'
  url:            https://twitter.com/mozzy16

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tcmorris.github.io