# Build settings
github:           [metadata]
repository:       tcmorris/tcmorris.github.io
markdown:         kramdown
highlighter:      rouge
paginate:         4
permalink:        pretty
exclude:          ["README.md", "Gemfile.lock", "Gemfile"]
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jemoji

# Basic info
title:            tcmorris
tagline:          '.net web developer'
description:      '.net web developer'
url:              https://tcmorris.net
enforce_ssl:      tcmorris.net
version:          1.1.0

# Custom vars
google:
  analytics:	    'UA-60083725-1'

disqus:
  username:		    'tcmorris'

meta:
  description:    'Thomas Morris is a web developer who specialises in Umbraco and ASP.NET'
  keywords:       'Web developer, umbraco, asp.net, c#, csharp, mvc'

author:
  name:           'Thomas Morris'
  email:		      'hello@tcmorris.net'
  twitter:        mozzy16
  image: 		      /public/images/thomasmorris.jpeg

umbraco:
  logo:           /public/images/umbraco_badge.jpg
  link:           https://umbraco.com/certified-partners/find-a-certified-developer/details?id=6bb58bc7-772d-4d71-99da-b924cb232066