# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            tcmorris
tagline:          '.net web developer'
description:      '.net web developer'
url:              http://tcmorris.net

google:
  analytics:	  'UA-60083725-1'

disqus:
  username:		  'tcmorris'

meta:
  description:    'Thomas Morris is a web developer who specialises in Umbraco and ASP.NET'
  keywords:       'Web developer, Umbraco, ASP.NET'
  
author:
  name:           'Thomas Morris'
  email:		  'hello@tcmorrs.net'
  twitter:        mozzy16

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tcmorris/tcmorris.github.io